"""TestAttempt table

Revision ID: 11306ce55599
Revises: eb4ad988193d
Create Date: 2021-05-07 16:54:27.699976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11306ce55599'
down_revision = 'eb4ad988193d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_attempt',
    sa.Column('attemptId', sa.Integer(), nullable=False),
    sa.Column('testId', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('attemptId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_attempt')
    # ### end Alembic commands ###
